# Generated by Django 2.0.2 on 2018-03-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestId',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_id', models.SlugField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('short_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('http_url', models.URLField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
