# Generated by Django 2.0.2 on 2018-03-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='httpurl',
            new_name='http_url',
        ),
    ]
